### ISSUE TITLE
Not able to get started with Unity/iOS

### ISSUE THREAD

**Issue by marcelschmidtdev** [nudge-now/sdk-unity#1]
I’m not able to get started with iOS SDK integration.
I did the following steps with our current Unity project, with a blank Unity project and a blank native Xcode project:
1.  Added SDK to project (imported Unity SDK to Unity project)
2.  Added following frameworks: SystemConfiguration, StoreKit, AdSupport, AdFresca
3.  Added „-ObjC“ to „other linker flags“
4.  Added path to AdFresca folder to „Header Search Paths“ and set option to „recursive“
5.  Disabled „Bitcode“
6.  Added "#import < AdFresca/AdFrescaView.h >“ and [AdFrescaView startSession:@„MY_API_KEY“] to „UnityAppController.mm“ (for native „AppDelegate.m“)
7.  Added the NSAppTransportSecurity dictionary to my Info.plist
I’m always getting this exception and the app crashes:
    **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM JSONRepresentation]: unrecognized selector sent to instance 0x13dede1c0'

I'm running Unity 5.1.2p3 and XCode 7.2

**Comment by nextofsearch** [comment]
Hi,

It seems 'SBJson' is not added to your Xcode project. 'SBJson' is located in our iOS SDK folder. Please don't forget to add 'Resources' folder in the same location as well. FYI, it would not happen if you have just drag-and-dropped our SDK folder into the project.

Please email us at support@nudge.do when you have a question.
